[versions]
agp = "8.10.1"
kotlin = "2.2.10"
composeMultiplatform = "1.9.0-beta03"
android-minSdk = "24"
android-compileSdk = "36"
android-targetSdk = "36"
playServicesAds = "24.6.0"

[libraries]
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
